import { useEffect, useRef } from "react";
import { NeatGradient, type NeatConfig } from "@firecms/neat";

// Hero background config (firecms/neat). Earthy warm browns + rust over a deep
// teal/navy base — the cinematic warm/cool look, with built-in grain.
export const HERO_NEAT_CONFIG: NeatConfig = {
  colors: [
    { color: "#573423", enabled: true },
    { color: "#A38266", enabled: true },
    { color: "#68615A", enabled: true },
    { color: "#091129", enabled: true },
    { color: "#854124", enabled: true },
  ],
  speed: 3,
  horizontalPressure: 5,
  verticalPressure: 7,
  waveFrequencyX: 2,
  waveFrequencyY: 2,
  waveAmplitude: 8,
  shadows: 6,
  highlights: 8,
  colorBrightness: 1,
  colorSaturation: 7,
  wireframe: false,
  colorBlending: 10,
  backgroundColor: "#004E64",
  backgroundAlpha: 1,
  grainScale: 3,
  grainSparsity: 0,
  grainIntensity: 0.3,
  grainSpeed: 1,
  resolution: 2,
  yOffset: 0,
  yOffsetWaveMultiplier: 8.5,
  yOffsetColorMultiplier: 7.8,
  yOffsetFlowMultiplier: 9,
  flowDistortionA: 0.4,
  flowDistortionB: 10,
  flowScale: 3.3,
  flowEase: 0.37,
  flowEnabled: true,
  enableProceduralTexture: false,
  transparentTextureVoid: false,
  textureVoidLikelihood: 0.06,
  textureVoidWidthMin: 10,
  textureVoidWidthMax: 500,
  textureBandDensity: 0.8,
  textureColorBlending: 0.06,
  textureSeed: 333,
  textureEase: 0.25,
  proceduralBackgroundColor: "#003FFF",
  textureShapeTriangles: 20,
  textureShapeCircles: 15,
  textureShapeBars: 15,
  textureShapeSquiggles: 10,
  domainWarpEnabled: true,
  domainWarpIntensity: 0.15,
  domainWarpScale: 2.8,
  vignetteIntensity: 0,
  vignetteRadius: 0.8,
  fresnelEnabled: false,
  fresnelPower: 2,
  fresnelIntensity: 0.5,
  fresnelColor: "#FFFFFF",
  iridescenceEnabled: false,
  iridescenceIntensity: 0.5,
  iridescenceSpeed: 1,
  bloomIntensity: 0,
  bloomThreshold: 0.7,
  chromaticAberration: 0,
  shapeType: "plane",
  shapeRotationX: 0.56,
  shapeRotationY: -3.141592653589793,
  shapeRotationZ: 3.141592653589793,
  shapeAutoRotateSpeedX: 0.2,
  shapeAutoRotateSpeedY: 0,
  sphereRadius: 15,
  torusRadius: 15,
  torusTube: 5,
  cylinderRadius: 10,
  cylinderHeight: 40,
  planeBend: 0,
  planeTwist: 0,
  silhouetteFade: 0.25,
  cylinderFade: 0.08,
  ribbonFade: 0.05,
  flatShading: true,
  cameraLock: true,
  cameraX: 0,
  cameraY: 0,
  cameraZ: 0,
  cameraRotationX: 0,
  cameraRotationY: 0,
  cameraRotationZ: 0,
  cameraZoom: 1,
};

// Footer background config — muted slate/stone tones over a blue base, slow flow,
// no grain.
export const FOOTER_NEAT_CONFIG: NeatConfig = {
  colors: [
    { color: "#15191A", enabled: true },
    { color: "#A4ADB2", enabled: true },
    { color: "#514A45", enabled: true },
    { color: "#2A3034", enabled: true },
    { color: "#7B6652", enabled: true },
    { color: "#FF9A9E", enabled: false },
  ],
  speed: 0.5,
  horizontalPressure: 5,
  verticalPressure: 4,
  waveFrequencyX: 0,
  waveFrequencyY: 3,
  waveAmplitude: 5,
  shadows: 5,
  highlights: 5,
  colorBrightness: 1,
  colorSaturation: 7,
  wireframe: false,
  colorBlending: 10,
  backgroundColor: "#003FFF",
  backgroundAlpha: 1,
  grainScale: 0,
  grainSparsity: 0,
  grainIntensity: 0,
  grainSpeed: 1,
  resolution: 2,
  yOffset: 9504,
  yOffsetWaveMultiplier: 1.8,
  yOffsetColorMultiplier: 4,
  yOffsetFlowMultiplier: 4,
  flowDistortionA: 0,
  flowDistortionB: 0.1,
  flowScale: 1.6,
  flowEase: 0.32,
  flowEnabled: true,
  enableProceduralTexture: false,
  transparentTextureVoid: false,
  textureVoidLikelihood: 0.29,
  textureVoidWidthMin: 120,
  textureVoidWidthMax: 420,
  textureBandDensity: 2.9,
  textureColorBlending: 0.06,
  textureSeed: 536,
  textureEase: 0.5,
  proceduralBackgroundColor: "#775454",
  textureShapeTriangles: 20,
  textureShapeCircles: 15,
  textureShapeBars: 15,
  textureShapeSquiggles: 10,
  domainWarpEnabled: false,
  domainWarpIntensity: 0,
  domainWarpScale: 3,
  vignetteIntensity: 0,
  vignetteRadius: 0.8,
  fresnelEnabled: false,
  fresnelPower: 2,
  fresnelIntensity: 0.5,
  fresnelColor: "#FFFFFF",
  iridescenceEnabled: false,
  iridescenceIntensity: 0.5,
  iridescenceSpeed: 1,
  bloomIntensity: 0,
  bloomThreshold: 0.7,
  chromaticAberration: 0,
  shapeType: "plane",
  shapeRotationX: 0,
  shapeRotationY: 0,
  shapeRotationZ: 0,
  shapeAutoRotateSpeedX: 0,
  shapeAutoRotateSpeedY: 0,
  sphereRadius: 15,
  torusRadius: 15,
  torusTube: 5,
  cylinderRadius: 10,
  cylinderHeight: 40,
  planeBend: 0,
  planeTwist: 0,
  silhouetteFade: 0.25,
  cylinderFade: 0.08,
  ribbonFade: 0.05,
  flatShading: true,
  cameraLock: true,
  cameraX: 0,
  cameraY: 0,
  cameraZ: 0,
  cameraRotationX: 0,
  cameraRotationY: 0,
  cameraRotationZ: 0,
  cameraZoom: 1,
};

// Renders a NeatGradient onto a canvas, wiring up the WebGL lifecycle (created
// once, destroyed on unmount) and reacting to scroll via the `yOffset` setter.
export function NeatBackground({
  config = HERO_NEAT_CONFIG,
  className,
}: {
  config?: NeatConfig;
  className?: string;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const gradient = new NeatGradient({ ref: canvas, ...config });

    const onScroll = () => {
      gradient.yOffset = window.scrollY;
    };
    window.addEventListener("scroll", onScroll, { passive: true });

    return () => {
      window.removeEventListener("scroll", onScroll);
      gradient.destroy();
    };
  }, [config]);

  return <canvas ref={canvasRef} aria-hidden className={className} style={{ width: "100%", height: "100%" }} />;
}
