/**
 * The editing runtime — Editor.js itself.
 *
 * Three things matter here.
 *
 *  1. THE CUSTOM BLOCKS MUST SURVIVE. Editor.js hands each block to the tool
 *     owning its `type`, and a tool that renders an empty node has its block
 *     judged empty and dropped. An agent's chart or matrix would be destroyed
 *     the first time someone opened the document to fix a typo. Every type
 *     present in the document is therefore guaranteed a tool, and every tool is
 *     guaranteed to render something.
 *  2. THE CUSTOM BLOCKS ARE REAL TOOLS, not placards. A callout is edited by
 *     typing in it and its tone is switched from the block settings menu; a
 *     chart is edited through its data. They carry toolbox entries, icons and
 *     settings like any native tool, because to the person writing there is no
 *     such thing as "the agent's blocks" and "mine".
 *  3. Saving is debounced, never fires on the initial render, and refuses to
 *     persist a document that lost most of its blocks.
 */
import { createElement, useEffect, useRef, useState } from "react";
import { createRoot, type Root } from "react-dom/client";
import { flushSync } from "react-dom";
import EditorJS, { type BlockToolConstructable, type OutputData } from "@editorjs/editorjs";
import Header from "@editorjs/header";
import List from "@editorjs/list";
import ImageTool from "@editorjs/image";
import Table from "@editorjs/table";
import Quote from "@editorjs/quote";
import Code from "@editorjs/code";
import Delimiter from "@editorjs/delimiter";
import Checklist from "@editorjs/checklist";
import Warning from "@editorjs/warning";
import Embed from "@editorjs/embed";
import Raw from "@editorjs/raw";
import Marker from "@editorjs/marker";
import InlineCode from "@editorjs/inline-code";
import Underline from "@editorjs/underline";
import { cn } from "@/lib/utils";
import { type ArtifactDocument } from "./blocks";
import { Block } from "./BlockRenderer";
import "./editor.css";

/* ------------------------------------------------------------------ icons */
/** Editor.js draws toolbox and settings entries from raw SVG strings. */
const svg = (d: string) =>
  `<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${d}</svg>`;
const ICONS = {
  kpi: svg('<rect x="3" y="4" width="7" height="16" rx="1"/><rect x="14" y="4" width="7" height="16" rx="1"/>'),
  chart: svg('<path d="M3 3v18h18"/><rect x="7" y="12" width="3" height="6"/><rect x="13" y="8" width="3" height="10"/>'),
  banner: svg('<rect x="3" y="4" width="18" height="8" rx="2"/><path d="M3 17h12M3 21h8"/>'),
  comparison: svg('<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16M3 10h18"/>'),
  matrix: svg('<path d="M4 20V4M4 20h16"/><circle cx="9" cy="14" r="1.6"/><circle cx="16" cy="8" r="1.6"/>'),
  callout: svg('<circle cx="12" cy="12" r="9"/><path d="M12 8v5M12 16h.01"/>'),
  slide: svg('<rect x="2" y="4" width="20" height="13" rx="2"/><path d="M8 21h8"/>'),
  block: svg('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18"/>'),
  edit: svg('<path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z"/>'),
  tone: svg('<circle cx="13.5" cy="6.5" r="2.5"/><circle cx="17.5" cy="14.5" r="2.5"/><circle cx="6.5" cy="12.5" r="4.5"/>'),
};

/** Inline formatting offered on every text-bearing block. */
const INLINE = ["bold", "italic", "underline", "marker", "inlineCode", "link"];

/**
 * Types Editor.js provides on its own, which must therefore never be claimed by
 * the catch-all. Registering `paragraph` here is the substitution that takes the
 * whole editor down if the import resolves to a namespace instead of a class —
 * so it is left to the core, and simply protected from being overwritten.
 */
const BUNDLED = new Set(["paragraph"]);

/* ---------------------------------------------------------- custom blocks */

/** Tones a callout can take, in the order the settings menu offers them. */
const TONES = [
  { key: "info", label: "Information" },
  { key: "success", label: "Confirmation" },
  { key: "warning", label: "Vigilance" },
  { key: "danger", label: "Alerte" },
] as const;

/**
 * A data block, drawn by the renderer the reader sees, editable as JSON.
 *
 * A chart or a matrix has no sensible inline editing gesture — you do not type
 * a scatter plot. But "not typeable" must not mean "not editable": the settings
 * menu opens the block's data in place, and the block redraws on blur. The
 * alternative, a grey placard saying "chart (generated by the agent)", made the
 * editor a downgrade of the reader.
 */
function dataTool(type: string, label: string, icon: string): BlockToolConstructable {
  return class {
    private data: Record<string, unknown>;
    private root: Root | null = null;
    private host: HTMLElement | null = null;
    static get isReadOnlySupported() { return true; }
    static get toolbox() { return { title: label, icon }; }
    /**
     * Without this the block is DELETED on open: Editor.js decides emptiness
     * from the DOM, and a tool that declares `validate` is trusted instead of
     * measured. The data is the truth here, not the rendering.
     */
    validate() { return true; }
    constructor({ data }: { data: Record<string, unknown> }) { this.data = data ?? {}; }

    private draw() {
      const host = this.host!;
      this.root?.unmount();
      host.innerHTML = "";
      this.root = createRoot(host);
      // SYNCHRONOUS on purpose: Editor.js reads the node right after render()
      // and a normal React render has not painted by then.
      //
      // Guarded, because this root is DETACHED: it shares no context with the
      // app, and a component of ours that throws here throws inside the effect
      // that mounts the editor — which unmounts the whole page. One block must
      // never be able to do that, so a failure degrades to a placard.
      try {
        flushSync(() => this.root!.render(createElement(Block, { block: { type, data: this.data } })));
      } catch (err) {
        console.error(`[artifact] le bloc « ${type} » n'a pas pu être rendu`, err);
        try { this.root.unmount(); } catch { /* already torn down */ }
        this.root = null;
        host.innerHTML = "";
      }
      if (host.childNodes.length === 0) {
        host.innerHTML = `<div class="rounded-lg border border-dashed border-border px-3 py-6 text-center text-xs text-muted-foreground">${label} — vide</div>`;
      }
    }

    /** Swap the rendering for its JSON, and back on blur. */
    private editJson() {
      const host = this.host!;
      this.root?.unmount();
      this.root = null;
      host.innerHTML = "";
      const ta = document.createElement("textarea");
      ta.value = JSON.stringify(this.data, null, 2);
      ta.spellcheck = false;
      ta.className =
        "w-full rounded-lg border border-primary/40 bg-muted/40 p-3 font-mono text-xs leading-relaxed outline-none";
      ta.rows = Math.min(24, ta.value.split("\n").length + 1);
      const commit = () => {
        try {
          const parsed = JSON.parse(ta.value);
          if (parsed && typeof parsed === "object") this.data = parsed as Record<string, unknown>;
        } catch {
          // Invalid JSON keeps the previous data rather than emptying the block.
        }
        this.draw();
      };
      ta.addEventListener("blur", commit);
      ta.addEventListener("keydown", (e) => { if (e.key === "Escape") { e.preventDefault(); this.draw(); } });
      host.appendChild(ta);
      ta.focus();
    }

    render() {
      const el = document.createElement("div");
      el.className = "my-3";
      el.contentEditable = "false";
      this.host = el;
      this.draw();
      return el;
    }
    renderSettings() {
      return [{ icon: ICONS.edit, label: "Modifier les données", onActivate: () => this.editJson() }];
    }
    destroy() {
      const r = this.root;
      this.root = null;
      // React refuses to unmount synchronously from inside a commit, which is
      // where Editor.js calls destroy().
      if (r) setTimeout(() => r.unmount(), 0);
    }
    save() { return this.data; }
  } as unknown as BlockToolConstructable;
}

/**
 * A callout: coloured box, text typed directly into it, tone in the settings.
 *
 * This one is written by hand rather than mounted from React because it is
 * genuinely editable — the caret has to live in the block, and a React tree
 * re-rendering under the caret fights it.
 */
class CalloutTool {
  private data: { tone: string; text: string };
  private wrap: HTMLElement | null = null;
  private body: HTMLElement | null = null;
  static get isReadOnlySupported() { return true; }
  static get toolbox() { return { title: "Encadré", icon: ICONS.callout }; }
  constructor({ data }: { data: Partial<{ tone: string; text: string }> }) {
    this.data = { tone: String(data?.tone ?? "info"), text: String(data?.text ?? "") };
  }
  private paint() {
    const tone = TONES.some((t) => t.key === this.data.tone) ? this.data.tone : "info";
    const skin: Record<string, string> = {
      info: "border-sky-500/30 bg-sky-500/10 text-sky-950 dark:text-sky-100",
      success: "border-emerald-500/30 bg-emerald-500/10 text-emerald-950 dark:text-emerald-100",
      warning: "border-amber-500/30 bg-amber-500/10 text-amber-950 dark:text-amber-100",
      danger: "border-rose-500/30 bg-rose-500/10 text-rose-950 dark:text-rose-100",
    };
    this.wrap!.className = `my-3 rounded-xl border-l-4 px-4 py-3 text-sm leading-relaxed ${skin[tone]}`;
  }
  render() {
    this.wrap = document.createElement("div");
    this.body = document.createElement("div");
    this.body.contentEditable = "true";
    this.body.dataset.placeholder = "Ce qu'il faut retenir…";
    this.body.className = "outline-none";
    this.body.innerHTML = this.data.text;
    this.wrap.appendChild(this.body);
    this.paint();
    return this.wrap;
  }
  renderSettings() {
    return TONES.map((t) => ({
      icon: ICONS.tone,
      label: t.label,
      isActive: this.data.tone === t.key,
      closeOnActivate: true,
      onActivate: () => { this.data.tone = t.key; this.paint(); },
    }));
  }
  save() { return { tone: this.data.tone, text: this.body?.innerHTML ?? this.data.text }; }
  validate(data: { text?: string }) { return typeof data?.text === "string" && data.text.trim().length > 0; }
}

/**
 * A banner: the document's opening block. Title and subtitle typed in place.
 */
class BannerTool {
  private data: Record<string, unknown>;
  private title: HTMLElement | null = null;
  private sub: HTMLElement | null = null;
  static get isReadOnlySupported() { return true; }
  static get toolbox() { return { title: "Bandeau de titre", icon: ICONS.banner }; }
  constructor({ data }: { data: Record<string, unknown> }) { this.data = data ?? {}; }
  render() {
    const wrap = document.createElement("div");
    wrap.className = "my-3 rounded-2xl bg-gradient-to-br from-indigo-600 to-indigo-800 px-6 py-7 text-white";
    this.title = document.createElement("div");
    this.title.contentEditable = "true";
    this.title.className = "text-2xl font-semibold leading-tight outline-none";
    this.title.dataset.placeholder = "Titre du document";
    this.title.innerHTML = String(this.data.title ?? "");
    this.sub = document.createElement("div");
    this.sub.contentEditable = "true";
    this.sub.className = "mt-1.5 text-sm text-white/70 outline-none";
    this.sub.dataset.placeholder = "Sous-titre, date, périmètre…";
    this.sub.innerHTML = String(this.data.subtitle ?? "");
    wrap.append(this.title, this.sub);
    return wrap;
  }
  save() {
    return { ...this.data, title: this.title?.innerHTML ?? "", subtitle: this.sub?.innerHTML ?? "" };
  }
  validate(data: { title?: string }) { return typeof data?.title === "string" && data.title.trim().length > 0; }
}

/**
 * A slide break. It carries only a title, so it is a one-field block — and it
 * must never render empty, since an empty node is a deleted block and deleting
 * it silently reflows every page after it.
 */
class SlideTool {
  private title: HTMLElement | null = null;
  private data: Record<string, unknown>;
  static get isReadOnlySupported() { return true; }
  static get toolbox() { return { title: "Nouvelle page", icon: ICONS.slide }; }
  constructor({ data }: { data: Record<string, unknown> }) { this.data = data ?? {}; }
  render() {
    const wrap = document.createElement("div");
    wrap.className = "my-6 flex items-center gap-3 border-t-2 border-dashed border-primary/40 pt-3";
    const tag = document.createElement("span");
    tag.contentEditable = "false";
    tag.className = "shrink-0 rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-primary";
    tag.textContent = "page";
    this.title = document.createElement("div");
    this.title.contentEditable = "true";
    this.title.className = "flex-1 text-base font-semibold outline-none";
    this.title.dataset.placeholder = "Titre de la page";
    this.title.innerHTML = String(this.data.title ?? "");
    wrap.append(tag, this.title);
    return wrap;
  }
  save() { return { ...this.data, title: this.title?.innerHTML ?? "" }; }
  validate(data: { title?: string }) { return typeof data?.title === "string" && data.title.trim().length > 0; }
}

/** Data blocks with no inline editing gesture — edited through their JSON. */
const DATA_BLOCKS: Array<{ type: string; label: string; icon: string }> = [
  { type: "kpi", label: "Indicateurs clés", icon: ICONS.kpi },
  { type: "chart", label: "Graphique", icon: ICONS.chart },
  { type: "comparison", label: "Grille comparative", icon: ICONS.comparison },
  { type: "matrix", label: "Matrice de positionnement", icon: ICONS.matrix },
];

export function ArtifactEditor({ doc, onChange, readOnly, className }: {
  doc: ArtifactDocument;
  onChange?: (doc: ArtifactDocument) => void;
  readOnly?: boolean;
  className?: string;
}) {
  const holder = useRef<HTMLDivElement>(null);
  const editor = useRef<EditorJS | null>(null);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Mounting fires onChange in some versions; ignore anything before ready.
  const ready = useRef(false);
  // "mounting" until the editor reports in, then "live" — or "fallback" if it
  // came up without the document, in which case we show the reader instead.
  const [mode, setMode] = useState<"mounting" | "live" | "fallback">("mounting");

  useEffect(() => {
    if (!holder.current) return;
    ready.current = false;
    setMode("mounting");

    // ONE HOST PER MOUNT, and a flag for everything async.
    //
    // StrictMode mounts effects twice in development: instance A starts, the
    // cleanup schedules `isReady.then(destroy)` — which cannot run before A has
    // finished initialising — and instance B mounts meanwhile. A's late
    // `destroy()` then empties the holder, taking B's rendering with it. The
    // editor reported itself healthy over a DOM that had just been wiped: the
    // blank report, reproduced.
    //
    // Giving each mount its own child node means a late teardown can only ever
    // touch its own; `cancelled` keeps a stale instance from driving the state.
    let cancelled = false;
    const host = document.createElement("div");
    holder.current.appendChild(host);

    const tools: Record<string, unknown> = {
      // `paragraph` is deliberately NOT registered: Editor.js bundles it as the
      // default block, and overriding the default block is the one substitution
      // that takes the whole editor down if the import resolves to anything but
      // a class. It gains nothing here — the bundled tool is the same tool.
      header: { class: Header, inlineToolbar: INLINE, config: { levels: [1, 2, 3, 4], defaultLevel: 2 } },
      list: { class: List, inlineToolbar: INLINE, config: { defaultStyle: "unordered" } },
      checklist: { class: Checklist, inlineToolbar: INLINE },
      table: { class: Table, inlineToolbar: INLINE, config: { withHeadings: true } },
      quote: { class: Quote, inlineToolbar: INLINE, config: { quotePlaceholder: "Citation", captionPlaceholder: "Source" } },
      warning: { class: Warning, inlineToolbar: INLINE, config: { titlePlaceholder: "Point d'attention", messagePlaceholder: "Détail" } },
      code: Code,
      raw: Raw,
      delimiter: Delimiter,
      embed: { class: Embed, config: { services: { youtube: true, vimeo: true, figma: true, miro: true, codepen: true } } },
      // Uploads are not wired: agents reference images by URL, and a paste-by-url
      // field is the honest affordance until a storage endpoint exists here.
      image: {
        class: ImageTool, inlineToolbar: INLINE,
        config: { uploader: { uploadByUrl: (url: string) => Promise.resolve({ success: 1, file: { url } }) } },
      },
      // Inline tools — what the selection toolbar offers.
      marker: Marker,
      inlineCode: InlineCode,
      underline: Underline,
    };

    tools.callout = CalloutTool as unknown as BlockToolConstructable;
    tools.banner = BannerTool as unknown as BlockToolConstructable;
    tools.slide = SlideTool as unknown as BlockToolConstructable;
    for (const b of DATA_BLOCKS) tools[b.type] = dataTool(b.type, b.label, b.icon);

    // CATCH-ALL. Registering the types we happen to know about is not enough:
    // Editor.js drops any block whose type has no tool, so one forgotten name —
    // a block added later, a document from an older shape — silently deletes
    // content on open. Derive the list from the DOCUMENT instead of a constant,
    // and every type present is guaranteed a tool, known or not.
    //
    // …with ONE exception: the tools Editor.js bundles itself. `paragraph` is
    // not in `tools` because the core provides it as the default block, so the
    // catch-all happily claimed it and every paragraph in the document became a
    // read-only card you could only edit as JSON. A missing entry here means
    // "the core has it", not "nobody has it".
    for (const b of doc.blocks) {
      if (!tools[b.type] && !BUNDLED.has(b.type)) tools[b.type] = dataTool(b.type, b.type, ICONS.block);
    }

    // Drop any tool whose import did not resolve to a constructor. Editor.js
    // throws during init on a malformed tool and leaves the holder empty, so a
    // single bad interop default looked exactly like "the editor deleted
    // everything". Losing one block type beats losing the whole editor.
    for (const [name, t] of Object.entries(tools)) {
      const cls = (t as { class?: unknown })?.class ?? t;
      if (typeof cls !== "function") {
        console.warn(`[artifact] outil « ${name} » indisponible — bloc rendu en lecture seule`);
        tools[name] = dataTool(name, name, ICONS.block);
      }
    }
    // Name the imports that did not resolve to a class. Every wipe so far has
    // been one bad import, and the symptom — a blank page — never said which.
    const broken = Object.entries(tools)
      .filter(([, t]) => typeof ((t as { class?: unknown })?.class ?? t) !== "function")
      .map(([n]) => n);
    if (broken.length) console.error("[artifact] outils non résolus :", broken.join(", "));

    const instance = new EditorJS({
      holder: host,
      data: { blocks: doc.blocks } as OutputData,
      readOnly,
      minHeight: 120,
      autofocus: false,
      placeholder: "Écrivez, ou tapez / pour insérer un bloc…",
      inlineToolbar: INLINE,
      tools: tools as never,
      onReady: () => {
        if (cancelled) return;
        ready.current = true;
        // THE SAFETY NET. One misbehaving tool takes the whole document down —
        // that has happened more than once — and the failure looks identical to
        // "the app deleted my report". Count what actually mounted: if the
        // editor swallowed the document, fall back to the read-only rendering,
        // which needs no tools and cannot fail this way. The content stays on
        // screen and nothing is written back.
        const mounted = instance.blocks?.getBlocksCount?.() ?? 0;
        if (doc.blocks.length > 2 && mounted < doc.blocks.length / 2) {
          console.error(`[artifact] ${doc.blocks.length} blocs dans le document, ${mounted} montés — passage en lecture seule`);
          setMode("fallback");
        } else {
          setMode("live");
        }
      },
      onChange: async () => {
        if (!onChange || readOnly || !ready.current || cancelled) return;
        if (timer.current) clearTimeout(timer.current);
        timer.current = setTimeout(async () => {
          try {
            const out = await instance.save();
            const next = out.blocks as ArtifactDocument["blocks"];
            // REFUSE to persist a gutted document. Guard on LOSS, not just on
            // emptiness: a partial drop still looked like a legitimate edit, and
            // the debounce wrote the truncation 600 ms later. Deleting most of a
            // document is never something a human does in one keystroke.
            if (doc.blocks.length > 2 && next.length < doc.blocks.length / 2) {
              console.error(
                `[artifact] ${doc.blocks.length} blocs à l'ouverture, ${next.length} après montage — sauvegarde annulée pour ne pas perdre le document`,
              );
              return;
            }
            // Mounting is not editing. Editor.js emits a change as it settles,
            // so simply opening a report rewrote its row — every open another
            // chance for a bad build to overwrite good content. Write only when
            // the document actually differs from what was loaded.
            const before = JSON.stringify(doc.blocks.map((b) => [b.type, b.data]));
            const after = JSON.stringify(next.map((b) => [b.type, b.data]));
            if (before === after) return;
            // Spread `doc` first: the document carries fields the editor knows nothing
            // about (the cover), and rebuilding the object from scratch dropped them.
            onChange({ ...doc, time: out.time, version: out.version, blocks: next });
          } catch { /* a save that fails must not break typing */ }
        }, 600);
      },
    });
    editor.current = instance;

    // `onReady` is not a guarantee — it simply never fires when init throws, and
    // that is precisely the case that left a blank page. Catch the rejection,
    // and time out in case neither path resolves.
    instance.isReady.catch((err) => {
      if (cancelled) return;
      console.error("[artifact] l'éditeur n'a pas pu s'initialiser — document affiché en lecture seule", err);
      setMode("fallback");
    });
    const bail = setTimeout(() => {
      if (!ready.current && !cancelled) {
        console.error("[artifact] l'éditeur n'a pas répondu — document affiché en lecture seule");
        setMode("fallback");
      }
    }, 4000);

    return () => {
      cancelled = true;
      clearTimeout(bail);
      if (timer.current) clearTimeout(timer.current);
      // destroy() is absent on a failed init; guard rather than throw on unmount.
      instance.isReady
        .then(() => instance.destroy?.())
        .catch(() => {})
        .finally(() => host.remove());
      editor.current = null;
    };
    // Remounts only on a different document — not on every keystroke.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [readOnly]);

  // CONTENT FIRST, EDITOR SECOND.
  //
  // The editor used to be the only thing rendered, so anything that went wrong
  // inside it — a bad import, a tool that throws, an init that never resolves —
  // showed up as a blank page and read as "the app deleted my report". Here the
  // document is painted immediately by the renderer, which depends on no tools
  // and cannot fail that way, and the editor only replaces it once it has
  // reported in with the right number of blocks. A failure now costs editing,
  // never the content.
  const live = mode === "live";
  return (
    <div className={cn("artifact-editor relative", className)} data-mode={mode}>
      <div
        ref={holder}
        className={cn(!live && "pointer-events-none absolute inset-x-0 top-0 -z-10 opacity-0")}
        aria-hidden={!live}
      />
      {!live && (
        <div className="space-y-3">
          {mode === "fallback" && (
            <p className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-xs text-amber-900 dark:text-amber-100">
              Ce document ne s'ouvre pas dans l'éditeur : il est affiché en lecture seule et n'a pas été modifié.
            </p>
          )}
          {doc.blocks.map((b, i) => <Block key={b.id ?? i} block={b} />)}
        </div>
      )}
    </div>
  );
}

export default ArtifactEditor;
