{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relay.fullname" . }}
  labels: {{- include "relay.labels" . | nindent 4 }}
type: Opaque
stringData:
  RELAY_TOKEN: {{ required "relayToken (ou existingSecret) est requis" .Values.relayToken | quote }}
{{- end }}
