-- 0254_report_toolbar_floating.sql
--
-- GENERATED by scripts/gen-report-artisan-migration.mjs — do not edit by hand.
-- Source: report-artisan-src/ (28 kB of engine,
-- 3 playbooks).

-- ── Le moteur ───────────────────────────────────────────────────────────────
-- Les fichiers du moteur qui ont changé : report.css.
-- En lignes plutôt qu'en module partagé pour ne pas traîner 450 ko dans le
-- bundle de chaque edge function, et plutôt qu'en objets storage pour qu'un
-- environnement neuf soit complet après `supabase db push`, sans téléversement.

insert into public.report_artisan_assets (name, content) values
  ('report.css', $RA_ASSET$/* ============================================================
   Report Artisan — design system
   Tokens first, roles everywhere. Light + dark are both
   *selected*, never an automatic flip.
   ============================================================ */

:root {
  /* --- surfaces & ink (light) --- */
  --page:        #f7f6f3;
  --surface:     #ffffff;
  --surface-2:   #fbfaf8;
  --ink:         #14131a;
  --ink-2:       #55535e;
  --ink-3:       #8b8996;
  --hairline:    #e7e4de;
  --hairline-2:  #f0eeea;
  --shadow:      0 1px 2px rgba(20,19,26,.04), 0 8px 24px -12px rgba(20,19,26,.10);
  --shadow-lg:   0 2px 4px rgba(20,19,26,.04), 0 24px 56px -24px rgba(20,19,26,.18);

  /* --- accent (overridden per theme preset) --- */
  --accent:      #2a78d6;
  --accent-ink:  #1c5cab;
  --accent-soft: #eaf2fd;
  --on-accent:   #ffffff;

  /* --- categorical series (validated set, light steps) --- */
  --s1: #2a78d6; --s2: #eb6834; --s3: #1baf7a; --s4: #eda100;
  --s5: #e87ba4; --s6: #008300; --s7: #4a3aa7; --s8: #e34948;

  /* --- status (fixed, never themed) --- */
  --ok: #0ca30c; --warn: #fab219; --serious: #ec835a; --critical: #d03b3b;
  --ok-text: #006300;

  /* --- chart chrome --- */
  --grid:     #e6e4dd;
  --axis:     #c6c3ba;
  --chart-bg: transparent;

  /* --- type --- */
  --font-body: "Inter", system-ui, -apple-system, "Segoe UI", sans-serif;
  --font-display: "Instrument Serif", Georgia, "Times New Roman", serif;
  --font-ui: system-ui, -apple-system, "Segoe UI", sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace;

  /* --- geometry --- */
  --col: 760px;
  --col-bleed: 900px;
  --col-wide: 1060px;
  --r-sm: 6px; --r: 10px; --r-lg: 16px; --r-xl: 24px;

  color-scheme: light;
}

[data-theme="dark"] {
  --page:        #0d0d0d;
  --surface:     #171717;
  --surface-2:   #1e1e1d;
  --ink:         #f7f6f3;
  --ink-2:       #c3c2b7;
  --ink-3:       #898781;
  --hairline:    #2c2c2a;
  --hairline-2:  #232322;
  --shadow:      0 1px 2px rgba(0,0,0,.4), 0 8px 24px -12px rgba(0,0,0,.6);
  --shadow-lg:   0 2px 4px rgba(0,0,0,.4), 0 24px 56px -24px rgba(0,0,0,.7);

  --accent-soft: rgba(57,135,229,.14);

  --s1: #3987e5; --s2: #d95926; --s3: #199e70; --s4: #c98500;
  --s5: #d55181; --s6: #008300; --s7: #9085e9; --s8: #e66767;

  --ok-text: #0ca30c;
  --grid:  #2c2c2a;
  --axis:  #383835;

  color-scheme: dark;
}

/* --- accent presets ------------------------------------------------ */
[data-accent="blue"]   { --accent:#2a78d6; --accent-ink:#1c5cab; --accent-soft:#eaf2fd; }
[data-accent="indigo"] { --accent:#4a3aa7; --accent-ink:#372a80; --accent-soft:#eeecfa; }
[data-accent="teal"]   { --accent:#0f8f79; --accent-ink:#0a6b5b; --accent-soft:#e6f5f2; }
[data-accent="green"]  { --accent:#1baf7a; --accent-ink:#13805a; --accent-soft:#e7f6f0; }
[data-accent="amber"]  { --accent:#b8730a; --accent-ink:#8d5806; --accent-soft:#fbf1e2; }
[data-accent="rose"]   { --accent:#c9385c; --accent-ink:#9c2846; --accent-soft:#fcecf0; }
[data-accent="plum"]   { --accent:#8a3fa0; --accent-ink:#6a2f7c; --accent-soft:#f6ecf9; }
[data-accent="slate"]  { --accent:#3f4a5a; --accent-ink:#2b3442; --accent-soft:#eef0f3; }

[data-theme="dark"][data-accent="blue"]   { --accent:#5d9ceb; --accent-ink:#8fbcf2; --accent-soft:rgba(93,156,235,.16); }
[data-theme="dark"][data-accent="indigo"] { --accent:#9085e9; --accent-ink:#b3abf1; --accent-soft:rgba(144,133,233,.16); }
[data-theme="dark"][data-accent="teal"]   { --accent:#3fbfa6; --accent-ink:#71d2be; --accent-soft:rgba(63,191,166,.16); }
[data-theme="dark"][data-accent="green"]  { --accent:#3fc793; --accent-ink:#74d8b2; --accent-soft:rgba(63,199,147,.16); }
[data-theme="dark"][data-accent="amber"]  { --accent:#e0a33c; --accent-ink:#ecc077; --accent-soft:rgba(224,163,60,.16); }
[data-theme="dark"][data-accent="rose"]   { --accent:#ec6f8f; --accent-ink:#f39cb2; --accent-soft:rgba(236,111,143,.16); }
[data-theme="dark"][data-accent="plum"]   { --accent:#c07ad4; --accent-ink:#d5a3e2; --accent-soft:rgba(192,122,212,.16); }
[data-theme="dark"][data-accent="slate"]  { --accent:#8fa0b8; --accent-ink:#b3c0d1; --accent-soft:rgba(143,160,184,.16); }

/* --- type presets --------------------------------------------------- */
[data-type="modern"]    { --font-display: "Inter", system-ui, sans-serif; }
[data-type="editorial"] { --font-display: "Instrument Serif", Georgia, serif; }

/* ============================================================
   Base
   ============================================================ */
* { box-sizing: border-box; }

html { -webkit-text-size-adjust: 100%; }

body {
  margin: 0;
  background: var(--page);
  color: var(--ink);
  font-family: var(--font-body);
  font-size: 17px;
  line-height: 1.65;
  font-feature-settings: "kern" 1, "liga" 1, "calt" 1;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

::selection { background: var(--accent-soft); }

.ra-shell { min-height: 100vh; padding: 0 20px 120px; }

.ra-paper {
  max-width: var(--col-wide);
  margin: 0 auto;
  background: var(--surface);
  border: 1px solid var(--hairline);
  border-radius: var(--r-xl);
  box-shadow: var(--shadow-lg);
  overflow: hidden;
}

.ra-body { padding: 0 clamp(20px, 5vw, 72px) 88px; }

/* ============================================================
   Document masthead (title, subtitle, meta)
   ============================================================ */
.ra-masthead { padding: clamp(36px, 6vw, 68px) 0 clamp(20px, 3vw, 32px); }

.ra-eyebrow {
  font-family: var(--font-ui);
  font-size: 12px;
  font-weight: 600;
  letter-spacing: .1em;
  text-transform: uppercase;
  color: var(--accent);
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 18px;
}
.ra-eyebrow::before {
  content: "";
  width: 22px; height: 2px;
  background: currentColor;
  border-radius: 2px;
  opacity: .55;
}

.ra-title {
  font-family: var(--font-display);
  font-size: clamp(38px, 6vw, 62px);
  line-height: 1.04;
  font-weight: 400;
  letter-spacing: -0.02em;
  margin: 0 0 16px;
  max-width: 18ch;
  text-wrap: balance;
}
[data-type="modern"] .ra-title { font-weight: 660; letter-spacing: -0.035em; }

.ra-subtitle {
  font-size: clamp(17px, 2vw, 20px);
  line-height: 1.5;
  color: var(--ink-2);
  margin: 0 0 30px;
  max-width: 60ch;
  text-wrap: pretty;
}

.ra-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 10px 28px;
  padding-top: 22px;
  border-top: 1px solid var(--hairline);
  font-family: var(--font-ui);
  font-size: 13px;
}
.ra-meta__item { display: flex; flex-direction: column; gap: 2px; }
.ra-meta__k { color: var(--ink-3); font-size: 11px; letter-spacing: .07em; text-transform: uppercase; font-weight: 600; }
.ra-meta__v { color: var(--ink); font-weight: 500; }


/* ============================================================
   Sources — stacked favicons that unfold into named links
   ============================================================
   Collapsed, a citation costs one line-height: the marks overlap like a stack
   of cards. Hovered (or focused, for the keyboard), the stack fans out and each
   mark names itself. Nothing is hidden behind the hover — every name is in the
   title attribute, and the whole pill is still a set of real links. */
.ra-sources {
  display: inline-flex;
  align-items: center;
  vertical-align: middle;
  max-width: 100%;
  flex-wrap: wrap;
  gap: 0;
}
.ra-src {
  display: inline-flex;
  align-items: center;
  gap: 0;
  max-width: 100%;
  padding: 2px;
  border: 1px solid var(--hairline);
  border-radius: 999px;
  background: var(--surface);
  color: var(--ink-2);
  text-decoration: none;
  font-family: var(--font-ui);
  font-size: 12px;
  font-weight: 560;
  line-height: 1;
  transition: margin .18s ease, background .12s ease, border-color .12s ease, box-shadow .12s ease;
}
.ra-src + .ra-src { margin-left: -11px; }
.ra-src__ico {
  width: 18px; height: 18px;
  border-radius: 999px;
  object-fit: contain;
  background: var(--surface-2);
  flex: none;
}
/* No favicon reachable at build time: a monogram, tinted from the name so the
   same source keeps the same colour across every report. */
.ra-src__ico--mono {
  display: inline-flex; align-items: center; justify-content: center;
  font-size: 10px; font-weight: 700; color: #fff;
  background: hsl(var(--mono-h, 210deg) 52% 46%);
}
.ra-src__name {
  max-width: 0;
  opacity: 0;
  overflow: hidden;
  white-space: nowrap;
  transition: max-width .22s ease, opacity .16s ease, padding .22s ease;
  padding: 0;
}
.ra-sources:hover .ra-src,
.ra-sources:focus-within .ra-src { margin-left: 4px; }
.ra-sources:hover .ra-src:first-child,
.ra-sources:focus-within .ra-src:first-child { margin-left: 0; }
.ra-sources:hover .ra-src__name,
.ra-sources:focus-within .ra-src__name { max-width: 14rem; opacity: 1; padding: 0 8px 0 6px; }
a.ra-src:hover { border-color: var(--accent); color: var(--ink); box-shadow: 0 1px 6px -2px var(--accent-soft); }
a.ra-src:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }

/* Inline citation under a passage — pulled up so it reads as belonging to the
   paragraph above rather than floating between two of them. */
.ra-cite {
  display: flex; align-items: center; gap: 8px; flex-wrap: wrap;
  margin: -10px 0 0;
}
.ra-tool--sources { margin-top: -14px; }
.ra-tool--sources .ra-tool-bar { display: none; }
.ra-cite__label {
  font-family: var(--font-ui); font-size: 11px; font-weight: 600;
  letter-spacing: .06em; text-transform: uppercase; color: var(--ink-3);
}
.ra-sources--meta { margin-top: 1px; }

/* Printed, a hover affordance is worthless and a URL is not: every source
   names itself, in full. */
@media print {
  .ra-src + .ra-src { margin-left: 4px; }
  .ra-src:first-child { margin-left: 0; }
  .ra-src__name { max-width: none; opacity: 1; padding: 0 8px 0 6px; }
}

/* ============================================================
   Prose
   ============================================================ */
/* Every top-level block sits in the reading column; blocks that carry a
   .ra-bleed element (banners, charts, full-width figures) widen instead of
   being cropped — a wider measure is what makes a chart legible. */
.ra-static-block { max-width: var(--col); margin-inline: auto; }
.ra-static-block.is-bleed { max-width: var(--col-bleed); }
#ra-editor { max-width: none; }

.ra-callout__text[contenteditable]:empty::before,
.ra-lead[contenteditable]:empty::before {
  content: attr(data-placeholder); color: var(--ink-3);
}

.ra-body h1, .ra-body h2, .ra-body h3, .ra-body h4,
.ce-header {
  font-family: var(--font-display);
  color: var(--ink);
  letter-spacing: -0.015em;
  text-wrap: balance;
}
[data-type="modern"] .ra-body h1, [data-type="modern"] .ra-body h2,
[data-type="modern"] .ra-body h3, [data-type="modern"] .ce-header { font-weight: 640; letter-spacing: -0.025em; }

.ra-body h2, h2.ce-header {
  font-size: clamp(27px, 3.4vw, 34px);
  line-height: 1.18;
  font-weight: 400;
  margin: 2.4em 0 .5em;
  padding-top: .5em;
}
.ra-body h3, h3.ce-header {
  font-size: 22px; line-height: 1.3; font-weight: 500;
  margin: 1.9em 0 .4em;
}
.ra-body h4, h4.ce-header {
  font-family: var(--font-ui);
  font-size: 13px; font-weight: 680;
  letter-spacing: .08em; text-transform: uppercase;
  color: var(--ink-3);
  margin: 2em 0 .5em;
}

.ra-body p, .ce-paragraph { margin: 0 0 1.1em; text-wrap: pretty; }
.ra-body a, .ce-paragraph a { color: var(--accent); text-decoration-color: color-mix(in srgb, var(--accent) 35%, transparent); text-underline-offset: 3px; }
.ra-body strong { font-weight: 620; }
.ra-body mark, .cdx-marker { background: color-mix(in srgb, var(--accent) 18%, transparent); padding: .1em .15em; border-radius: 3px; }

.ra-body ul, .ra-body ol { padding-left: 1.3em; margin: 0 0 1.2em; }
.ra-body li { margin: .35em 0; }
.ra-body li::marker { color: var(--ink-3); }

.ra-lead {
  font-size: 20px; line-height: 1.55; color: var(--ink-2);
  border-left: 2px solid var(--accent);
  padding-left: 22px;
  margin: 0 0 1.6em;
}

/* ============================================================
   Banner
   ============================================================ */
.ra-banner {
  position: relative;
  width: 100%;
  border-radius: var(--r-lg);
  overflow: hidden;
  isolation: isolate;
  display: flex;
  align-items: flex-end;
  min-height: 220px;
  background: var(--surface-2);
}
.ra-banner--hero { border-radius: 0; margin: 0; min-height: 300px; }
.ra-banner__art { position: absolute; inset: 0; z-index: 0; }
.ra-banner__art svg, .ra-banner__art img { width: 100%; height: 100%; object-fit: cover; display: block; }
.ra-banner__scrim { position: absolute; inset: 0; z-index: 1; }
.ra-banner__inner {
  position: relative; z-index: 2;
  padding: clamp(24px, 4vw, 48px);
  width: 100%;
}
.ra-banner__eyebrow {
  font-family: var(--font-ui); font-size: 11.5px; font-weight: 650;
  letter-spacing: .12em; text-transform: uppercase;
  color: rgba(255,255,255,.82); margin-bottom: 10px;
}
.ra-banner__title {
  font-family: var(--font-display);
  font-size: clamp(28px, 4.4vw, 46px);
  line-height: 1.08; font-weight: 400; letter-spacing: -0.02em;
  color: #fff; margin: 0; max-width: 22ch; text-wrap: balance;
  text-shadow: 0 1px 24px rgba(0,0,0,.22);
}
[data-type="modern"] .ra-banner__title { font-weight: 650; letter-spacing: -0.03em; }
.ra-banner__sub { color: rgba(255,255,255,.86); margin: 12px 0 0; max-width: 52ch; font-size: 16px; }
.ra-banner--light .ra-banner__title { color: var(--ink); text-shadow: none; }

/* A section banner renders its title as an <h2>, which sits inside .ra-body and
   would otherwise inherit the prose heading colour and margins. These overrides
   carry higher specificity on purpose — do not lower it. */
.ra-body .ra-banner__title,
.ra-paper .ra-banner__title {
  color: #fff;
  margin: 0;
  padding-top: 0;
  font-size: clamp(28px, 4.4vw, 46px);
  line-height: 1.08;
  font-weight: 400;
  letter-spacing: -0.02em;
}
[data-type="modern"] .ra-body .ra-banner__title,
[data-type="modern"] .ra-paper .ra-banner__title { font-weight: 650; letter-spacing: -0.03em; }
.ra-body .ra-banner--light .ra-banner__title,
.ra-paper .ra-banner--light .ra-banner__title { color: var(--ink); text-shadow: none; }
.ra-banner--light .ra-banner__eyebrow { color: var(--accent); }
.ra-banner--light .ra-banner__sub { color: var(--ink-2); }

/* ============================================================
   KPI tiles
   ============================================================ */
.ra-kpis {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(168px, 1fr));
  gap: 1px;
  background: var(--hairline);
  border: 1px solid var(--hairline);
  border-radius: var(--r);
  overflow: hidden;
  margin: 2em 0;
}
.ra-kpi {
  background: var(--surface);
  padding: 20px 22px 18px;
  display: flex; flex-direction: column;
}
.ra-kpi__label {
  font-family: var(--font-ui); font-size: 11.5px; font-weight: 620;
  letter-spacing: .07em; text-transform: uppercase; color: var(--ink-3);
  margin-bottom: 10px;
}
.ra-kpi__value {
  font-family: var(--font-ui);
  font-size: 33px; line-height: 1.05; font-weight: 640;
  letter-spacing: -0.03em; color: var(--ink);
  display: flex; align-items: baseline; gap: 4px;
}
.ra-kpi__unit { font-size: 17px; font-weight: 550; color: var(--ink-2); letter-spacing: 0; }
.ra-kpi__delta {
  display: flex; align-items: baseline; flex-wrap: wrap; gap: 2px 5px;
  margin-top: 9px;
  font-family: var(--font-ui); font-size: 13px; font-weight: 560;
  color: var(--ink-2);
  overflow-wrap: anywhere;
}
.ra-kpi__delta svg { align-self: center; }
.ra-kpi__delta b { font-weight: inherit; white-space: nowrap; }
.ra-kpi__delta em { font-style: normal; color: var(--ink-3); font-weight: 450; }
.ra-kpi__label, .ra-kpi__note { overflow-wrap: anywhere; }
.ra-kpi__delta svg { width: 13px; height: 13px; flex: none; }
.ra-kpi__delta--up   { color: var(--ok-text); }
.ra-kpi__delta--down { color: var(--critical); }
.ra-kpi__note { margin-top: 8px; font-size: 12.5px; color: var(--ink-3); font-family: var(--font-ui); }
.ra-kpi__spark { margin-top: auto; padding-top: 14px; }
.ra-kpi__spark svg { display: block; width: 100%; height: 30px; overflow: visible; }

/* ============================================================
   Figures & charts
   ============================================================ */
.ra-figure { margin: 2.4em 0; }
.ra-figure__frame {
  background: var(--surface);
  border: 1px solid var(--hairline);
  border-radius: var(--r);
  padding: 22px 22px 16px;
}
.ra-figure__head { margin-bottom: 16px; }
.ra-figure__title {
  font-family: var(--font-ui); font-size: 15.5px; font-weight: 620;
  color: var(--ink); margin: 0; letter-spacing: -0.01em;
}
.ra-figure__sub { font-family: var(--font-ui); font-size: 13px; color: var(--ink-2); margin: 4px 0 0; }
.ra-figure__cap {
  font-family: var(--font-ui); font-size: 12.5px; color: var(--ink-3);
  margin: 10px 2px 0; line-height: 1.5;
}
.ra-figure__cap b { color: var(--ink-2); font-weight: 600; }

.ra-legend { display: flex; flex-wrap: wrap; gap: 6px 18px; margin: 14px 0 2px; }
.ra-legend__item {
  display: inline-flex; align-items: center; gap: 7px;
  font-family: var(--font-ui); font-size: 12.5px; color: var(--ink-2);
}
.ra-legend__swatch { width: 10px; height: 10px; border-radius: 3px; flex: none; }

.ra-chart { position: relative; }
.ra-chart svg { display: block; width: 100%; height: auto; overflow: visible; }
.ra-chart text { font-family: var(--font-ui); }

.ra-tip {
  position: absolute; z-index: 20; pointer-events: none;
  background: var(--ink); color: var(--page);
  border-radius: var(--r-sm);
  padding: 8px 11px;
  font-family: var(--font-ui); font-size: 12.5px; line-height: 1.45;
  box-shadow: var(--shadow);
  opacity: 0; transform: translate(-50%, -112%);
  transition: opacity .12s ease;
  white-space: nowrap;
}
.ra-tip[data-show="1"] { opacity: 1; }
.ra-tip__k { font-weight: 640; display: block; margin-bottom: 2px; }
.ra-tip__row { display: flex; align-items: center; gap: 7px; }
.ra-tip__sw { width: 8px; height: 8px; border-radius: 2px; flex: none; }
.ra-tip__v { margin-left: auto; font-variant-numeric: tabular-nums; font-weight: 600; padding-left: 12px; }

/* image figures */
.ra-figure__img { width: 100%; display: block; border-radius: var(--r); background: var(--surface-2); }
.ra-figure--full .ra-figure__img { border-radius: var(--r-lg); }
.ra-imgfallback {
  width: 100%; aspect-ratio: 16/9; border-radius: var(--r);
  display: flex; align-items: center; justify-content: center;
  color: var(--ink-3); font-family: var(--font-ui); font-size: 13px;
  background: linear-gradient(135deg, var(--accent-soft), var(--surface-2));
  border: 1px dashed var(--hairline);
}

/* ============================================================
   Callouts
   ============================================================ */
.ra-callout {
  display: flex; gap: 14px;
  border: 1px solid var(--hairline);
  border-left: 3px solid var(--accent);
  background: var(--surface-2);
  border-radius: var(--r);
  padding: 16px 18px;
  margin: 1.8em 0;
}
.ra-callout__icon { flex: none; width: 19px; height: 19px; margin-top: 2px; color: var(--accent); }
.ra-callout__icon svg { width: 100%; height: 100%; display: block; }
.ra-callout__body { flex: 1; min-width: 0; font-size: 15.5px; line-height: 1.6; color: var(--ink-2); }
.ra-callout__title {
  font-family: var(--font-ui); font-weight: 640; font-size: 14px;
  color: var(--ink); margin-bottom: 4px; letter-spacing: -0.005em;
}
.ra-callout--good     { border-left-color: var(--ok);       }
.ra-callout--good .ra-callout__icon     { color: var(--ok-text); }
.ra-callout--warn     { border-left-color: var(--warn);     }
.ra-callout--warn .ra-callout__icon     { color: #a9750a; }
.ra-callout--critical { border-left-color: var(--critical); }
.ra-callout--critical .ra-callout__icon { color: var(--critical); }
[data-theme="dark"] .ra-callout--warn .ra-callout__icon { color: var(--warn); }

/* ============================================================
   Tables
   ============================================================ */
.ra-table-wrap { margin: 2em 0; overflow-x: auto; }
.ra-table, .tc-table {
  width: 100%; border-collapse: collapse;
  font-family: var(--font-ui); font-size: 14.5px;
}
.ra-table th {
  text-align: left; font-weight: 620; color: var(--ink-3);
  font-size: 11.5px; letter-spacing: .07em; text-transform: uppercase;
  padding: 0 14px 10px; border-bottom: 1px solid var(--hairline);
}
.ra-table td {
  padding: 12px 14px; border-bottom: 1px solid var(--hairline-2);
  color: var(--ink-2); vertical-align: top;
}
.ra-table tr:last-child td { border-bottom: 0; }
.ra-table td:first-child { color: var(--ink); font-weight: 540; }
.ra-table .num { text-align: right; font-variant-numeric: tabular-nums; }

/* ============================================================
   Quotes / dividers / misc
   ============================================================ */
.ra-quote, .cdx-quote {
  margin: 2.2em 0; padding: 0 0 0 26px;
  border-left: 2px solid var(--accent);
}
.ra-quote__text, .cdx-quote__text {
  font-family: var(--font-display); font-size: 23px; line-height: 1.42;
  color: var(--ink); font-weight: 400;
}
[data-type="modern"] .ra-quote__text { font-weight: 520; letter-spacing: -0.015em; }
.ra-quote__by, .cdx-quote__caption {
  font-family: var(--font-ui); font-size: 13px; color: var(--ink-3);
  margin-top: 10px;
}

.ra-rule { border: 0; height: 1px; background: var(--hairline); margin: 3em 0; }
.ra-rule--dots {
  height: auto; background: none; text-align: center;
  color: var(--ink-3); letter-spacing: 1.1em; font-size: 12px;
}
.ra-rule--dots::before { content: "•••"; }

.ra-tag {
  display: inline-block;
  font-family: var(--font-ui); font-size: 11.5px; font-weight: 620;
  letter-spacing: .05em; text-transform: uppercase;
  padding: 4px 9px; border-radius: 100px;
  background: var(--accent-soft); color: var(--accent-ink);
}

.ra-footer {
  max-width: var(--col); margin: 4em auto 0; padding-top: 26px;
  border-top: 1px solid var(--hairline);
  font-family: var(--font-ui); font-size: 12.5px; color: var(--ink-3);
  display: flex; justify-content: space-between; gap: 16px; flex-wrap: wrap;
}

/* ============================================================
   Toolbar (edit mode chrome — never exported)
   ============================================================ */
.ra-bar {
  position: sticky; top: 0; z-index: 200;
  display: flex; align-items: center; gap: 8px; flex-wrap: wrap;
  padding: 10px clamp(14px, 3vw, 26px);
  background: color-mix(in srgb, var(--page) 88%, transparent);
  backdrop-filter: blur(14px) saturate(1.6);
  border-bottom: 1px solid var(--hairline);
  font-family: var(--font-ui);
}
.ra-bar__brand {
  font-size: 12.5px; font-weight: 620; color: var(--ink-2);
  display: flex; align-items: center; gap: 8px; margin-right: auto;
  min-width: 0;
}
.ra-bar__dot { width: 8px; height: 8px; border-radius: 50%; background: var(--accent); flex: none; }
.ra-bar__status { color: var(--ink-3); font-weight: 450; font-size: 12px; }
.ra-btn {
  display: inline-flex; align-items: center; gap: 6px;
  font-family: var(--font-ui); font-size: 12.5px; font-weight: 560;
  color: var(--ink-2); background: var(--surface);
  border: 1px solid var(--hairline); border-radius: 8px;
  padding: 7px 11px; cursor: pointer;
  transition: background .12s ease, color .12s ease, border-color .12s ease;
  white-space: nowrap;
}
.ra-btn:hover { background: var(--surface-2); color: var(--ink); border-color: var(--ink-3); }
.ra-btn svg { width: 14px; height: 14px; }
.ra-btn--primary { background: var(--accent); color: var(--on-accent); border-color: transparent; }
.ra-btn--primary:hover { background: var(--accent-ink); color: var(--on-accent); }
[data-theme="dark"] .ra-btn--primary { color: #10100f; }

/* block settings popovers inside custom tools */
/* The bar FLOATS above its block. Hidden with opacity alone it still took its
   place in the flow — a KPI row's eight fields wrapped over two or three lines
   of empty space above every block, which read as holes all over the report. */
.ra-tool { position: relative; }
.ra-tool-bar {
  position: absolute; left: 0; right: 0; bottom: calc(100% + 6px); z-index: 30;
  display: flex; flex-wrap: wrap; gap: 6px; align-items: center;
  padding: 8px; border-radius: 12px;
  border: 1px solid var(--hairline); background: var(--surface);
  box-shadow: 0 12px 32px rgba(0,0,0,.14);
  opacity: 0; pointer-events: none; transform: translateY(4px);
  transition: opacity .15s ease, transform .15s ease;
  font-family: var(--font-ui);
}
/* Bridge over the 6px gap so the pointer can travel from the block to the bar. */
.ra-tool-bar::after { content: ""; position: absolute; left: 0; right: 0; top: 100%; height: 8px; }
.ce-block:hover .ra-tool-bar, .ra-tool-bar:focus-within { opacity: 1; pointer-events: auto; transform: none; }
.ra-chip {
  font-family: var(--font-ui); font-size: 11.5px; font-weight: 550;
  border: 1px solid var(--hairline); background: var(--surface);
  color: var(--ink-2); border-radius: 100px; padding: 3px 10px; cursor: pointer;
}
.ra-chip:hover { border-color: var(--accent); color: var(--accent); }
.ra-chip[aria-pressed="true"] { background: var(--accent); border-color: var(--accent); color: var(--on-accent); }
.ra-input {
  font-family: var(--font-ui); font-size: 12.5px;
  border: 1px solid var(--hairline); background: var(--surface); color: var(--ink);
  border-radius: 6px; padding: 5px 8px; min-width: 0;
}
.ra-input--wide { width: 100%; }
.ra-editnote {
  font-family: var(--font-ui); font-size: 11.5px; color: var(--ink-3);
  margin-top: 8px;
}

/* ============================================================
   Editor.js integration
   ============================================================ */
.codex-editor { padding: 0 !important; }
.codex-editor__redactor { padding-bottom: 120px !important; }
.ce-block__content, .ce-toolbar__content { max-width: var(--col) !important; }
.ce-block__content:has(.ra-bleed) { max-width: var(--col-bleed) !important; }
.ce-paragraph { line-height: inherit; }
.ce-block--selected .ce-block__content { background: var(--accent-soft); border-radius: var(--r-sm); }
.ce-toolbar__plus, .ce-toolbar__settings-btn { color: var(--ink-2); }
.ce-popover { --color-background: var(--surface); --color-text-primary: var(--ink); border-color: var(--hairline) !important; }
.cdx-search-field { background: var(--surface-2) !important; border-color: var(--hairline) !important; }
/* Editor.js ships a spreadsheet-looking table; a report table wants rules,
   not a grid, so the vertical borders go and the rows keep a hairline. */
.tc-wrap {
  --color-border: transparent;
  --color-text-secondary: var(--ink-3);
  font-family: var(--font-ui); font-size: 14.5px;
  border: 0; margin: 1.6em 0;
}
.tc-table { border: 0; }
.tc-row { border-bottom: 1px solid var(--hairline-2); }
.tc-row:last-child { border-bottom: 0; }
.tc-row--heading { border-bottom: 1px solid var(--hairline); }
.tc-cell { color: var(--ink-2); padding: 12px 14px; border: 0; }
.tc-cell:first-child { padding-left: 0; color: var(--ink); font-weight: 540; }
.tc-row--heading .tc-cell {
  color: var(--ink-3); font-weight: 620; font-size: 11.5px;
  letter-spacing: .07em; text-transform: uppercase; padding-bottom: 10px;
}
.cdx-list { color: inherit; }
.ce-inline-toolbar { --color-background: var(--surface); }

/* ============================================================
   Print / PDF
   ============================================================ */
@media print {
  :root { --page: #fff; --surface: #fff; }
  body { background: #fff; font-size: 11pt; }
  .ra-bar, .ra-tool-bar, .ce-toolbar, .ra-editnote { display: none !important; }
  .ra-shell { padding: 0; }
  .ra-paper { border: 0; border-radius: 0; box-shadow: none; max-width: none; }
  .ra-body { padding: 0 12mm 12mm; }
  .ra-figure, .ra-kpis, .ra-callout, .ra-banner { break-inside: avoid; }
  h2, h3 { break-after: avoid; }
  a { color: inherit; text-decoration: none; }
}

@media (max-width: 700px) {
  body { font-size: 16px; }
  .ra-bar__brand { width: 100%; }
  .ra-bar__brand > span:not(.ra-bar__status) { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .codex-editor__redactor { padding-bottom: 60px !important; }
  .tc-wrap { overflow-x: auto; }
  .ra-shell { padding: 0 10px 60px; }
  .ra-paper { border-radius: var(--r-lg); }
  .ra-kpis { grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); }
  .ra-kpi__value { font-size: 27px; }
}

@media (prefers-reduced-motion: reduce) {
  * { animation: none !important; transition: none !important; }
}
$RA_ASSET$)
on conflict (name) do update set content = excluded.content, updated_at = now();

-- ── Les fiches du skill ─────────────────────────────────────────────────────
-- Lues à la demande avec read_skill_file(slug="report-artisan", path="…").

delete from public.agent_skill_files f
using public.agent_skills s
where s.id = f.skill_id and s.workspace_id is null and s.slug = 'report-artisan';

insert into public.agent_skill_files (skill_id, path, content, sort)
select s.id, v.path, v.content, v.sort
from public.agent_skills s
cross join (values
  ('content-schema.md', $RA_ASSET$# Schéma du contenu d'un rapport

Un rapport = une racine, que tu passes à `report_open`, puis une suite de blocs,
un `report_add_block` par bloc, dans l'ordre de lecture.

La racine — les arguments de `report_open` :

```jsonc
{
  "title":    "Refonte du parcours d'onboarding",   // requis — le <h1>
  "subtitle": "Bilan de mission — six semaines…",   // 1–2 phrases
  "eyebrow":  "Rapport de mission",                 // surtitre court
  "accent":   "indigo",   // blue|indigo|teal|green|amber|rose|plum|slate
  "typeface": "editorial", // editorial (serif) | modern (sans)
  "theme":    "light",     // light | dark  (l'utilisateur peut basculer)
  "locale":   "fr-FR",     // formatage des nombres
  "lang":     "fr",
  "footer":   "Novaris SAS — document interne",
  "meta": {                // affiché sous le sous-titre, ordre conservé
    "Client": "Novaris SAS",
    "Période": "3 juin — 15 juillet 2026",
    "Auteur": "Marco Kamga"
  },
  "sources": [             // déclarées UNE fois, citées partout par leur nom
    { "name": "Stack Overflow", "url": "https://survey.stackoverflow.co/2026/" },
    { "name": "BLS", "url": "https://www.bls.gov/ooh/computer-and-information-technology/" }
  ],
  "heroBanner": {          // optionnel mais recommandé
    "style": "aurora",
    "eyebrow": "Novaris · Produit",
    "title": "Six semaines pour diviser l'abandon par deux",
    "subtitle": "Ce que nous avons changé, ce que ça a produit."
  }
}
```

`blocks` n'est pas un argument : chaque bloc part dans son propre appel à
`report_add_block(block)`. Appelle-le dès que tu as les faits d'une partie — le
fil est compacté au fil du run, un chiffre non écrit dans un bloc est perdu.

Le titre de la bannière et le `title` du document **ne doivent pas être le
même texte** : la bannière porte la conclusion, le titre nomme le document.

---

## Blocs

Chaque bloc : `{ "type": "...", "data": { ... } }`.
Le HTML inline (`<b> <i> <a> <mark> <br>`) est accepté dans tous les champs de
texte courant.

### `lead` — chapô
```json
{ "type": "lead", "data": { "text": "Le tunnel perdait <b>68 %</b> des visiteurs…" } }
```
Trois phrases maximum. Répond à « pourquoi je devrais lire ça ».

### `paragraph`
```json
{ "type": "paragraph", "data": { "text": "Trois frictions expliquent…" } }
```

### `header`
```json
{ "type": "header", "data": { "level": 2, "text": "Ce qui bloquait" } }
```
`level` 2 = section, 3 = sous-section, 4 = étiquette en petites capitales.

### `list`
```json
{ "type": "list", "data": {
  "style": "ordered",
  "items": [
    "Texte simple",
    { "content": "<b>Élément</b> avec sous-liste",
      "items": ["sous-élément"] }
  ] } }
```
`style` : `unordered` (défaut) ou `ordered`. Les chaînes simples sont
converties automatiquement.

### `checklist`
```json
{ "type": "checklist", "data": { "items": [
  { "text": "Livré", "checked": true },
  "À faire"
] } }
```

### `kpis` — tuiles d'indicateurs
```json
{ "type": "kpis", "data": { "items": [
  { "label": "Taux d'abandon", "value": "31", "unit": "%",
    "deltaLabel": "−37 pts", "direction": "down", "good": true,
    "deltaNote": "vs mai", "spark": [68, 61, 52, 44, 37, 31] },
  { "label": "Inscriptions / semaine", "value": "1 240",
    "delta": 84, "good": true, "note": "record sur 18 mois" }
] } }
```
| Champ | Effet |
|---|---|
| `value` | Chaîne : tu contrôles le formatage (`"1 240"`, `"2:40"`, `"4,2 M€"`). |
| `unit` | Suffixe en plus petit, collé à la valeur. |
| `delta` | Nombre → affiché en pourcentage signé. |
| `deltaLabel` | Texte libre, prioritaire sur `delta` (pour « −37 pts », « +12 k€ »). |
| `direction` | `up`/`down`/`flat` — la flèche. Déduit de `delta` si absent. |
| `good` | `true` = vert, `false` = rouge. **Toujours l'indiquer** quand une baisse est une bonne nouvelle. |
| `deltaNote` | Précision grise après la variation (« vs mai »). |
| `note` | Ligne de contexte sous la variation. |
| `spark` | Série de nombres → micro-courbe en bas de tuile. |

**Longueurs.** Une tuile fait environ 170 px. Au-delà, le texte passe à la ligne
et déséquilibre la rangée — le validateur prévient : `label` ~26 caractères,
`deltaLabel` ~14, `deltaNote` ~14, `note` ~34. Écris « vs janvier », pas « vs la
cohorte de janvier ».

3 ou 4 tuiles. Cinq et plus : ce n'est plus un coup d'œil, c'est un tableau.

### `chart`
```json
{ "type": "chart", "data": {
  "type": "bar",
  "title": "Abandons par étape du tunnel",
  "subtitle": "Part des visiteurs entrés dans l'étape qui n'en sortent pas",
  "categories": ["Tarifs", "Création compte", "Vérif. e-mail"],
  "series": [
    { "name": "Avant (mai)",     "data": [22, 31, 24] },
    { "name": "Après (juillet)", "data": [18, 11, 6] }
  ],
  "valueFormat": { "suffix": " %" },
  "caption": "La vérification e-mail concentrait le quart des pertes."
} }
```

| Champ | Détail |
|---|---|
| `type` | `bar`, `hbar`, `line`, `area`, `stackedBar`, `donut`. |
| `categories` | Axe des abscisses (ou libellés de lignes en `hbar`). |
| `series` | `[{name, data[], color?}]`. `data` doit avoir la même longueur que `categories`. |
| `valueFormat` | `{prefix, suffix, decimals, compact}` — `compact: true` → « 1,2 k ». |
| `caption` | Ce que le graphique montre. Voir `charts.md`. |
| `height` | Hauteur du tracé (défaut 300, 280 pour `donut`). |
| `showValues` | `bar` uniquement : valeur au-dessus de chaque barre. |
| `percent` | `stackedBar` : normalise chaque colonne à 100 %. |
| `wide` | `false` = le graphique reste dans la colonne de texte. |
| `colorByCategory` | `hbar` : une couleur par ligne au lieu d'un aplat unique. À n'activer que si les lignes sont des entités que le lecteur suit ailleurs. |
| `target` | Ligne de référence en pointillés : `32` ou `{"value": 32, "label": "cible 32 %"}`. Disponible sur `bar`, `hbar`, `line`, `area`, `stackedBar`. Le moteur réserve la place du libellé et étend l'échelle si besoin. |
| `zero` | `false` sur `line`/`area` : l'axe ne démarre plus à zéro. À utiliser quand la variation utile est petite devant les valeurs. |
| `labelLast` | `false` : pas d'étiquette sur le dernier point d'une courbe. |
| `rowHeight` / `labelWidth` | `hbar` : réglages fins. La gouttière de libellés est calculée automatiquement ; ne la force que si le rendu le demande. |

Un libellé de catégorie `hbar` est tronqué au-delà de 34 caractères (le texte
complet reste en infobulle). Le validateur prévient : déplace le détail dans la
`caption` plutôt que de le laisser couper.

`showValues` est ignoré sur un `bar` à plusieurs séries — les étiquettes se
chevauchent dans une même catégorie, et l'infobulle porte déjà les valeurs.

`donut` prend `items` au lieu de `categories`/`series`. **Donne-lui des valeurs
absolues** : la part en pourcentage est calculée et affichée par le moteur. Si
tes valeurs sont déjà des pourcentages, le moteur le détecte et n'affiche pas la
part deux fois ; `showShare: false` force le comportement.
```json
{ "type": "chart", "data": {
  "type": "donut",
  "title": "Répartition du temps de mission",
  "items": [ { "name": "Audit", "value": 34 }, { "name": "Tests", "value": 26 } ],
  "centerValue": "240 h", "centerLabel": "au total",
  "valueFormat": { "suffix": " h" }
} }
```

### `banner` — bannière de section
```json
{ "type": "banner", "data": {
  "style": "waves", "eyebrow": "Chantier suivant",
  "title": "Rétention à 30 jours",
  "subtitle": "L'inscription n'est plus le goulot.",
  "height": 210, "light": false
} }
```
`light: true` → fond clair et texte sombre (pour `blueprint`).
`image: "https://…"` remplace le motif procédural par une photo.

### `callout` — encadré
```json
{ "type": "callout", "data": {
  "tone": "critical", "title": "Cause principale",
  "text": "Le lien expirait avant d'être cliqué dans <b>41 % des cas</b>."
} }
```
`tone` : `info` | `good` | `warn` | `critical` | `idea`.
`icon` : nom de pictogramme pour forcer autre chose que l'icône par défaut.

### `table`
```json
{ "type": "table", "data": {
  "withHeadings": true,
  "content": [
    ["Chantier", "Impact", "Charge", "Échéance"],
    ["Activation J+7", "+12 pts rétention", "3 semaines", "Septembre"]
  ] } }
```
Première ligne = en-têtes. Les colonnes numériques sont alignées à droite
automatiquement dans la version exportée. Quatre à six colonnes maximum.

### `figure` — image ou illustration
```json
{ "type": "figure", "data": {
  "src": "data:image/png;base64,…",
  "alt": "Parcours d'inscription avant refonte",
  "caption": "Le schéma remis à l'équipe le 12 juin.",
  "wide": true
} }
```
Sans `src`, le bloc affiche un aplat marqué avec le texte `alt` — utile comme
emplacement réservé quand l'image viendra plus tard.

### `sources` — citer un passage

```json
{ "type": "sources", "data": { "items": ["Stack Overflow", "BLS"] } }
```

Se pose **juste après** le passage qu'il appuie : paragraphe, tableau,
graphique. Les `items` sont les `name` déclarés à la racine — le lien et le
logo du site sont repris de là.

Rendu : les logos se superposent en une petite pastille ; au survol elle se
déplie et chaque source devient une pastille nommée, cliquable vers sa page. À
l'impression, tout est déplié.

| Champ | Effet |
|---|---|
| `items` | Noms déclarés dans `sources`, ou `{name, url}` pour une source ponctuelle. |
| `label` | Surtitre facultatif (« Sources », « Méthode »). Vide par défaut. |

Le logo est récupéré à la construction et **intégré au fichier** : il s'affiche
hors ligne. Une source sans `url`, ou dont le logo est introuvable, porte un
monogramme coloré — la citation reste lisible, elle perd juste sa marque.

Cite ce qui porte un CHIFFRE ou une AFFIRMATION contestable. Un bloc de sources
après chaque paragraphe est un rapport qu'on ne lit plus.

### `quote`
```json
{ "type": "quote", "data": {
  "text": "On savait qu'on perdait des gens.",
  "caption": "Léa Marchand, Head of Growth" } }
```

### `delimiter`
```json
{ "type": "delimiter", "data": {} }
```
Séparateur discret. Utile avant une annexe ou une note de fin.

---

## Validation

`report_publish()` valide avant de construire, et refuse d'écrire un fichier
qu'un lecteur ne pourrait pas lire.

Les erreurs bloquent la publication, les avertissements sont des remarques de rédaction
(graphique sans titre, sans légende, trop de tuiles KPI, rapport sans aucun
graphique). Ils méritent presque toujours une correction plutôt qu'un haussement
d'épaules.
$RA_ASSET$, 0),
  ('charts.md', $RA_ASSET$# Graphiques

Un graphique est **lu par des gens** et **exécuté par toi**. Ce qui suit
transforme « fais joli » en décisions vérifiables.

## 1. Choisir la forme d'abord

La question n'est pas « quel graphique ? » mais « quel est le travail de cette
donnée ? ».

| Travail | Forme | Pourquoi |
|---|---|---|
| Comparer des catégories | `bar` | La longueur depuis une base commune est ce que l'œil compare le mieux. |
| Classer, libellés longs | `hbar` | Les libellés se lisent horizontalement, sans rotation. |
| Évolution dans le temps | `line` | La pente est le message. |
| Évolution + volume | `area` | Une seule série ; deux aires superposées deviennent illisibles. |
| Composition qui évolue | `stackedBar` | Ajoute `percent: true` si seule la part compte. |
| Répartition d'un tout | `donut` | 3 à 6 parts. Au-delà, un `hbar` est plus lisible. |
| Un seul chiffre | *pas un graphique* | Une tuile `kpis`. |

Si tu hésites entre deux formes, c'est souvent que le graphique essaie de dire
deux choses. Fais-en deux.

## 2. Les règles non négociables

**Un seul axe de valeurs.** Jamais deux échelles verticales dans un même
graphique — c'est l'erreur la plus fréquente et la plus trompeuse. Deux mesures
d'ordres de grandeur différents → deux graphiques, ou une indexation base 100.

**La couleur suit l'entité, jamais le rang.** « Avant » garde sa couleur d'un
graphique à l'autre. Un `hbar` trié du plus grand au plus petit reçoit un aplat
unique (le comportement par défaut) : colorier chaque barre différemment
suggère une identité qui n'existe pas.

**Légende dès deux séries.** Une série unique n'en a pas besoin — le titre la
nomme, et le moteur la peint dans la couleur d'accent du rapport.

**Huit séries maximum**, et en pratique quatre. Au-delà, regroupe la queue en
« Autres » ou fais des petits multiples. Le build refuse plus de huit.

**Pas de valeur sur chaque point.** Étiqueter tout revient à n'étiqueter rien.
Le moteur étiquette le dernier point d'une courbe ; `showValues: true` sur un
`bar` ne se justifie que si les valeurs exactes sont le sujet.

## 3. Montrer le seuil

Un rapport de pilotage tourne presque toujours autour d'une valeur de référence :
une cible de marge, un SLA, un budget, un seuil d'alerte. Un lecteur qui doit
faire la comparaison de tête la fait mal.

```jsonc
"target": 32                                   // trait pointillé + « cible 32 % »
"target": { "value": 32, "label": "cible marge" }
```

Le moteur étend l'échelle si la cible sort du domaine des données, réserve une
gouttière à droite pour le libellé, et dessine le trait au-dessus de la grille
mais sous les marques. Disponible sur `bar`, `hbar`, `line`, `area`,
`stackedBar`.

Une seule ligne de référence par graphique. Deux seuils sur un même tracé, c'est
deux graphiques ou un tableau.

## 4. Régler les nombres

`valueFormat` s'applique aux axes, aux étiquettes et aux infobulles :

```jsonc
{ "suffix": " %" }                    // 31 %
{ "prefix": "€", "decimals": 0 }      // €1 240
{ "compact": true }                   // 1,2 k  ·  3,4 M
{ "suffix": " j", "decimals": 1 }     // 4,5 j
```

Le séparateur et la virgule décimale suivent `locale` (`fr-FR` par défaut).

Pour les axes de temps longs (12 mois, 52 semaines), le moteur n'affiche qu'une
étiquette sur N pour éviter le chevauchement — n'essaie pas de raccourcir les
libellés toi-même, écris-les en clair.

## 5. La légende de lecture (`caption`)

C'est le champ le plus important et le plus souvent bâclé.

Mauvais : « Évolution des inscriptions par semaine. » — le titre le dit déjà.
Bon : « L'inflexion de la semaine 21 correspond à la mise en production de la
file d'envoi dédiée. »

Une bonne légende désigne **ce qu'il faut voir** : un point d'inflexion, une
exception, une limite méthodologique, un ordre de grandeur. Si tu n'as rien à
dire de plus que le titre, le graphique ne mérite peut-être pas sa place.

## 6. Ce que le moteur fait déjà pour toi

- palette catégorielle validée pour les daltonismes courants, avec une variante
  propre au mode sombre (pas un simple inversement) ;
- infobulle au survol sur toutes les formes, plus un `<title>` natif qui
  fonctionne même sans JavaScript ;
- grille et axes discrets, marques fines, coins arrondis côté valeur,
  espacement de 2 px entre segments empilés ;
- le texte reste en encre neutre : jamais un libellé coloré à la couleur de sa
  série, c'est la pastille qui porte l'identité.

Tu n'as donc rien à régler côté couleur. Concentre-toi sur la forme, l'échelle
et la légende.

## 7. Après le rendu, regarde

Le validateur contrôle la structure, pas la géométrie. Ouvre le fichier (ou
capture-le) et vérifie :

- des étiquettes d'axe qui se chevauchent → moins de catégories, ou `hbar` ;
- un titre de graphique qui passe à la ligne bizarrement → raccourcis-le, le
  contexte va dans `subtitle` ;
- une aire qui écrase une variation réelle → l'échelle démarre peut-être à zéro
  alors que la variation est de 2 % ; passe en `line` avec `"zero": false` ;
- un donut dont deux parts font 1 % → regroupe-les ;
- des étiquettes de fin de courbe superposées → le moteur en supprime une quand
  deux séries finissent à moins de 7 % d'écart, mais trois séries serrées
  restent illisibles : augmente `height`, ou passe la série de contexte en
  `labelLast: false` ;
- des libellés `hbar` coupés → ils dépassent 34 caractères ; raccourcis-les et
  mets le détail dans la `caption`.

Une remarque d'outillage : si `playwright` est disponible (souvent le cas),
ouvre le fichier en Chromium headless et prends une capture pleine page. C'est
le seul moyen fiable de voir un chevauchement. Écris les captures dans un
dossier propre à ton exécution — pas dans `/tmp/shot.png`, que d'autres
processus écrasent.
$RA_ASSET$, 1),
  ('gallery.md', $RA_ASSET$# Galerie — bannières, accents, pictogrammes

Tout est **procédural** : les bannières sont dessinées en SVG à partir de la
couleur d'accent et du thème. Changer `accent` ou basculer en mode sombre
redessine la galerie entière, de façon cohérente. Aucun fichier image, aucune
requête réseau, aucun droit d'auteur à gérer.

## Bannières

| Style | Allure | Va bien avec |
|---|---|---|
| `aurora` | nappes floues qui se croisent | par défaut ; stratégie, bilan, produit |
| `glow` | une lueur douce, très épuré | rapport sobre, note de direction |
| `waves` | vagues superposées | croissance, progression, cycles |
| `ribbon` | rubans souples qui traversent | parcours, flux, transformation |
| `arcs` | cercles concentriques décentrés | portée, cible, périmètre |
| `grid` | grille en perspective | technique, infrastructure |
| `topo` | courbes de niveau | analyse, exploration, cartographie |
| `dots` | trame de points en dégradé | données, échantillon, enquête |
| `prism` | éclats translucides superposés | créatif, marque, lancement |
| `strata` | bandes horizontales dégradées | couches, segments, paliers |
| `bars` | silhouette de barres | reporting chiffré, finance |
| `blueprint` | grille technique fine, fond clair | spécification, audit — utiliser avec `"light": true` |

Une bannière hero en tête, une ou deux bannières de section pour marquer une
bascule dans le récit. Trois ou plus et elles cessent de signifier quoi que ce
soit.

Le `title` d'une bannière est court et affirmatif — c'est une phrase qu'on
retient, pas un intitulé de chapitre. Le `subtitle` peut préciser.

Champ `seed` : deux bannières du même style dans un même rapport se ressemblent
(le tirage est déterministe et dérivé du titre). Donne un `seed` différent si
tu veux varier la composition sans changer de style.

## Accents

| Accent | Registre |
|---|---|
| `blue` | neutre, institutionnel, financier |
| `indigo` | produit, tech, conseil |
| `teal` | santé, environnement, opérations |
| `green` | croissance, durabilité, résultats |
| `amber` | retail, énergie, alerte maîtrisée |
| `rose` | marque, marketing, culture interne |
| `plum` | recherche, création, prospective |
| `slate` | juridique, gouvernance, austère |

Chaque accent a une déclinaison claire et une déclinaison sombre, choisies pour
garder le contraste dans les deux modes. Pour une charte client, remplace les
valeurs dans le bloc `[data-accent="…"]` de `assets/report.css` — c'est le seul
endroit à modifier.

La palette des graphiques est **indépendante** de l'accent : elle est validée
pour rester distinguable en cas de daltonisme, et ne change pas quand tu changes
d'accent. C'est voulu — un rapport rose ne doit pas rendre ses graphiques
illisibles.

## Pictogrammes

Disponibles pour `callout.icon` (l'icône par défaut découle du `tone`) :

`info` · `check` · `alert` · `stop` · `bulb` · `target` · `trendUp` ·
`trendDown` · `arrowUp` · `arrowDown` · `minus` · `clock` · `users` · `euro` ·
`chart` · `doc` · `flag` · `lock` · `globe` · `spark` · `layers` · `calendar` ·
`search` · `building`

Trait de 1,75 px sur une grille de 24 : ils s'accordent au texte sans le
concurrencer. N'en mets pas ailleurs que dans les encadrés — un pictogramme par
titre de section transforme un rapport en présentation.

## Typographie

`editorial` (défaut) : titres en Instrument Serif, texte en Inter. Chaleureux,
mémorable, adapté à un livrable qu'on lit.
`modern` : tout en Inter, resserré. Neutre, adapté à un reporting récurrent ou
à une charte déjà très sans-serif.

Les polices viennent de Google Fonts avec repli sur les polices système : hors
ligne, le document reste correct, simplement moins caractérisé.
$RA_ASSET$, 2)
) as v(path, content, sort)
where s.workspace_id is null and s.slug = 'report-artisan';
